Compatibility fixes. Upgrade PrettyTime so that String.isEmpty() (?!?!?) doesn't throw a NoSuchMethodError on pre Gingerbread devices, and remove references to getActionBar() from app